### ISSUE TITLE
Fake Processing Account

### ISSUE THREAD

**Issue by ranouf** [payload-code/payload-csharp#3]
Hi,

I m testing your API, is it possible to setup a fake processing account to be able to make a payment? I would like to avoid to set up the test environnement with real data, just in case a mistake happened.

Thanks

**Comment by ianhalpern** [comment]
@ranouf Thanks for reaching out and testing out the platform. You can just fill in dummy data for setting up a processing account from your test environment. Let us know if you're able to get a test account setup, also feel free to reach out directly too we're happy to jump on an integration call to talk through any implementation details.

**Comment by ranouf** [comment]
Thanks for fast answering, I will try that

**Comment by ranouf** [comment]
Hi,

so the dummy processing account has been created, its status is now in pending: 
![image](https://user-images.githubusercontent.com/1764519/89343016-a4a2c280-d671-11ea-9395-5e3becb8aa22.png)

I got an issue when I do a payment in Sandbox environment:

> Payload.pl+InvalidAttributes: processing_account_id

I took the one at the top here:
![image](https://user-images.githubusercontent.com/1764519/89343229-f8151080-d671-11ea-922a-93a739763cfe.png)

and my code is:
```
 var payment = pl.Payment.create(new
                {
                    amount,
                    processing_account_id = "XXXXXX",
                    payment_method = new pl.Card(new
                    {
                        card_number = cardNumber
                    })
                });
```

Do I need to wait until the status pass to validated to be able to test the payment? Or did I miss something?

Thanks

**Comment by ianhalpern** [comment]
@ranouf 
I think you just need to change `processing_account_id` to `processing_id`. In sandbox it's ok to use with the status of pending. Let me know if that did the trick.
```
var payment = pl.Payment.create(new
                {
                    amount = amount,
                    processing_id = "XXXXXX",
                    payment_method = new pl.Card(new
                    {
                        card_number = cardNumber
                    })
                });
```

**Comment by ranouf** [comment]
![image](https://user-images.githubusercontent.com/1764519/89587258-490e3b80-d80f-11ea-927f-ce53a8c00ffc.png)

I will try thanks but the documentation seems to not be correct.

**Comment by ranouf** [comment]
Hi,

Thanks, with your modification, it works!

Do you know the list of properties available after the payment?
Currently I have "status" and "id", is there other?

**Comment by ianhalpern** [comment]
@ranouf thank you for bringing the typo in the docs to our attention, much appreciated! Also, glad to hear it worked. Regarding the properties for a transaction object here's a list of the available properties, is this what you're looking for?

https://docs.payload.co/object-reference/#transactions
